name: Package
on:
  workflow_call:
    inputs:
      repository:
        description: 'repository'
        required: true
        type: string
    secrets:
      KEY:
        required: true
      SECRET:
        required: true
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl -s -H "Authorization: token ${{ secrets.PAT }}" \
          https://api.github.com/repos/${{ inputs.repository }}/tags \
          | jq -r '.[0].name')
          echo "Latest tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Run publish
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.KEY }} -Pgradle.publish.secret=${{ secrets.SECRET }} -Partifact_version=${{ steps.get_latest_tag.outputs.tag }}