name: Publish Dependency
on:
  push:
    tags:
      - "*"
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/publish-dependency.yml@main
    with:
      repository: "intisy"
    secrets:
      envPAT: ${{ secrets.PAT }}