name: Update Dependency README
on:
  release:
    types: [published]
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/readme-dependency.yml@main
    with:
      ref_name: ${{ github.ref_name }}
    secrets:
      envPAT: ${{ secrets.PAT }}