name: Release Java
on:
  push:
    branches:
      - main
      - master
jobs:
  call-reusable-workflow:
    uses: intisy/workflows/.github/workflows/release-java.yml@main
    with:
      repository: ${{ github.repository }}
    secrets:
      envPAT: ${{ secrets.PAT }}