name: Build And Upload
on:
  workflow_call:
    inputs:
      ref_name:
        description: 'ref_name'
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  build-and-upload:
    # runs-on: ubuntu-latest
    runs-on: windows-2019 # windows seems to work better for building gradle
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up BellSoft Liberica JDK 1.8 (Full)
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '8'
          architecture: 'x64'
          cache: 'gradle'

      - name: Setup Git
        run: echo ${{ secrets.envPAT }} | gh auth login --with-token
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Debug Releases
        run: gh release list

      - name: Create Release and Upload Jar
        run: |
            gh release create ${{ inputs.ref_name }} -t "Release ${{ inputs.ref_name }}"
            gh release upload "${{ inputs.ref_name }}" build/libs/* --clobber