name: Update Dependency README
on:
  workflow_call:
    inputs:
      repository:
        description: 'repository'
        required: true
        type: string
      actor:
        description: 'actor'
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(curl -s -H "Authorization: token ${{ secrets.envPAT }}" https://api.github.com/repos/${{ inputs.repository }}/tags | jq -r '.[].name' | grep -E '^[0-9]+(\.[0-9]+)*$' | sort -V | tail -n1)
          echo "Latest tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Update README
        id: update_readme
        run: |
          repo=$(echo "${{ inputs.repository }}" | cut -d'/' -f2)
          cat <<EOF > README.md
          # $(grep "^$display_name=" "gradle.properties" | cut -d'=' -f2-)
          
          Archives containing JAR files are available as [releases](https://github.com/${{ inputs.repository }}/releases).
          
          ## Usage in private repos (faster)
          
           * Maven (inside the `pom.xml` file)
          \`\`\`xml
            <repository>
                <id>github</id>
                <url>https://maven.pkg.github.com/${{ inputs.repository }}</url>
                <snapshots><enabled>true</enabled></snapshots>
            </repository>
            <dependency>
                <groupId>io.github.intisy</groupId>
                <artifactId>$repo</artifactId>
                <version>${{ steps.get_latest_tag.outputs.tag }}</version>
            </dependency>
          \`\`\`
          
           * Maven (inside the `settings.xml` file)
          \`\`\`xml
            <servers>
                <server>
                    <id>github</id>
                    <username>your-username</username>
                    <password>your-access-token</password>
                </server>
            </servers>
          \`\`\`
          
           * Gradle (inside the `build.gradle.kts` or `build.gradle` file)
          \`\`\`groovy
            repositories {
                maven {
                    url "https://maven.pkg.github.com/${{ inputs.repository }}"
                    credentials {
                        username = "<your-username>"
                        password = "<your-access-token>"
                    }
                }
            }
            dependencies {
                implementation 'io.github.${{ inputs.actor }}:$repo:${{ steps.get_latest_tag.outputs.tag }}'
            }
          \`\`\`
          
          ## Usage in public repos (slower and only works in gradle but safer)
          
           * Gradle (inside the `build.gradle.kts` or `build.gradle` file)
          \`\`\`groovy
            plugins {
                id "io.github.${{ inputs.actor }}.$repo" version "${{ steps.get_latest_tag.outputs.tag }}"
            }
            dependencies {
                githubImplementation "${{ inputs.actor }}:$repo:${{ steps.get_latest_tag.outputs.tag }}"
            }
          \`\`\`
          
          ## License
          
          [![Apache License 2.0](https://img.shields.io/badge/License-Apache_2.0-blue.svg)](LICENSE)
          EOF
          
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Auto-update README'
          add: 'README.md'
          new_branch: main
          committer_name: github-actions[bot]
          committer_email: github-actions[bot]@users.noreply.github.com