name: Release
on:
  workflow_call:
    inputs:
      ref_name:
        description: 'ref_name'
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Git
        run: echo ${{ secrets.envPAT }} | gh auth login --with-token

      - name: Debug Releases
        run: gh release list

      - name: Loop through files and create releases
        run: gh release create ${{ inputs.ref_name }} -t "Release ${{ inputs.ref_name }}"