name: Release
on:
  workflow_call:
    inputs:
      repository:
        description: 'repository'
        required: true
        type: string
    secrets:
      envPAT:
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Git
        run: echo ${{ secrets.envPAT }} | gh auth login --with-token

      - name: Debug Releases
        run: gh release list

      - name: Loop through files and create releases
        run: |
          for file in releases/*; do
            file_name="${file##*/}"
            full_repo=${{ inputs.repository }}
            repo="${full_repo##*/}"
            echo "Uploading $file_name"
            middle=$(echo "$file_name" | awk -F'-' '{print $2}')
            release_name="${middle%.jar}"
            echo "Using tag $release_name"
            if gh release view "$release_name" > /dev/null 2>&1; then
              echo "Release '$release_name' already exists. Skipping..."
              continue
            fi
            echo "Creating release '$release_name'..."
            gh release create "$release_name" --title "$release_name" --notes "Release created from file $file" "$file"
            cd releases
            mv $file_name $repo
            gh release upload "$release_name" $file --clobber
            mv $repo $file_name
          done