name: Tests

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/scripts/**'
  pull_request:
    paths:
      - '.github/scripts/**'

jobs:
  scripts:
    uses: ./.github/workflows/python-tests.yml
